-- ១. បង្កើតតារាងសម្រាប់មុខម្ហូប (Menu)
-- ១. បង្កើតតារាងសម្រាប់មុខម្ហូប (menu)
CREATE TABLE public.menu (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    price NUMERIC NOT NULL,
    image_url TEXT
);

-- ២. បង្កើតតារាងសម្រាប់ការកុម្ម៉ង់ (orders)
CREATE TABLE public.orders (
    id TEXT PRIMARY KEY,
    customer TEXT NOT NULL,
    items TEXT NOT NULL,
    total TEXT NOT NULL,
    status TEXT DEFAULT 'ថ្មី (រង់ចាំការបញ្ជាក់)',
    chat_id TEXT,
    receipt_url TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ៣. បង្កើតតារាងសម្រាប់អតិថិជន (users)
CREATE TABLE public.users (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    phone TEXT NOT NULL,
    points INT DEFAULT 0,
    chat_id TEXT
);